### ISSUE TITLE
no longer works on lxd 2.0.2

### ISSUE THREAD

**Issue by sebguilbaud** [aarnaud/collectd-lxc#2]
the script crashes with the following error, after outputting lots of good statistics : 

```
{'values': [436], 'plugin_instance': '0__prod-main-pg2', 'type_instance': 'ops_read', 'type': 'gauge', 'plugin': 'lxc_blkio'}
{'values': [0], 'plugin_instance': '0__prod-main-pg2', 'type_instance': 'ops_write', 'type': 'gauge', 'plugin': 'lxc_blkio'}
Traceback (most recent call last):
  File "./collectd_lxc.py", line 167, in <module>
    reader()
  File "./collectd_lxc.py", line 118, in reader
    with Namespace(container_PID, 'net'):
  File "/usr/local/lib/python2.7/dist-packages/nsenter/__init__.py", line 69, in __init__
    self.target_fd = Path(pid).open()
  File "/usr/local/lib/python2.7/dist-packages/pathlib.py", line 1077, in open
    return io.open(str(self), mode, buffering, encoding, errors, newline)
IOError: [Errno 21] Is a directory: '.'
```

I've tracked the origin of the bug here, it tries to find the container's pid, which no longer resides in `tasks` but in `init.scope/tasks` (IHMO)

The plugin _seems_ to work with the following crude hack : 

```
--- collectd_lxc.py 2016-09-07 16:51:49.040269863 +0200
+++ /etc/collectd/plugins/collectd_lxc.py   2016-09-07 16:48:13.570307507 +0200
@@ -112,7 +112,7 @@

                 ### Network
                     #PID lxc: cat /sys/fs/cgroup/devices/lxc/CONTAINER-NAME/tasks | head -n 1
-                    with open(os.path.join(metrics[user_id][container_name][metric], 'tasks'), 'r') as f:
+                    with open(os.path.join(metrics[user_id][container_name][metric], 'init.scope/tasks'), 'r') as f:
                         # The first line is PID of container
                         container_PID = f.readline().rstrip()
                         with Namespace(container_PID, 'net'):
```

**Comment by aarnaud** [comment]
Hi,

Thanks for the callback.

Can you push a merge request ?

Thanks

**Comment by sebguilbaud** [comment]
done
